### ISSUE TITLE
What version of commandwhitelist works perfectly with 1.8?

### ISSUE THREAD

**Issue by ftita** [YouHaveTrouble/CommandWhitelist#37]
`Unexpected exception while parsing console command "cw add default hotrest"
org.bukkit.command.CommandException: Unhandled exception executing command 'cw' in plugin CommandWhitelist v1.7.8
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:627) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:412) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:375) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [server.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_302]
Caused by: java.lang.NoSuchMethodError: org.bukkit.entity.Player.updateCommands()V
        at eu.endermite.commandwhitelist.spigot.config.ConfigCache.addCommand(ConfigCache.java:65) ~[?:?]
        at eu.endermite.commandwhitelist.spigot.command.MainCommand.onCommand(MainCommand.java:33) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[server.jar:git-Spigot-db6de12-18fbb24]
        ... 8 more`
        
       What version of commandwhitelist works perfectly with 1.8?
       I found some bugs in the latest version with 1.8.8 in use
